# Generated by Django 3.2.11 on 2022-01-18 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='token_auth.instructor'),
        ),
    ]
